<?php

namespace Container04h7zbA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFahrtkostenTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FahrtkostenType' shared autowired service.
     *
     * @return \App\Form\FahrtkostenType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FahrtkostenType.php';

        return $container->privates['App\\Form\\FahrtkostenType'] = new \App\Form\FahrtkostenType();
    }
}
