<?php

namespace ContainerBE0whLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_USpJZaWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uSpJZaW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uSpJZaW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fahrtkosten' => ['privates', '.errored..service_locator.uSpJZaW.App\\Entity\\Fahrtkosten', NULL, 'Cannot autowire service ".service_locator.uSpJZaW": it references class "App\\Entity\\Fahrtkosten" but no such service exists.'],
            'fahrtkostenRepository' => ['privates', 'App\\Repository\\FahrtkostenRepository', 'getFahrtkostenRepositoryService', true],
        ], [
            'fahrtkosten' => 'App\\Entity\\Fahrtkosten',
            'fahrtkostenRepository' => 'App\\Repository\\FahrtkostenRepository',
        ]);
    }
}
