<?php

namespace ContainerBE0whLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X778Am7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X778Am7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X778Am7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FahrtkostenController::delete' => ['privates', '.service_locator.uSpJZaW', 'get_ServiceLocator_USpJZaWService', true],
            'App\\Controller\\FahrtkostenController::edit' => ['privates', '.service_locator.uSpJZaW', 'get_ServiceLocator_USpJZaWService', true],
            'App\\Controller\\FahrtkostenController::index' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'App\\Controller\\FahrtkostenController::new' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'App\\Controller\\FahrtkostenController::show' => ['privates', '.service_locator.eHfDAxz', 'get_ServiceLocator_EHfDAxzService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\FahrtkostenController:delete' => ['privates', '.service_locator.uSpJZaW', 'get_ServiceLocator_USpJZaWService', true],
            'App\\Controller\\FahrtkostenController:edit' => ['privates', '.service_locator.uSpJZaW', 'get_ServiceLocator_USpJZaWService', true],
            'App\\Controller\\FahrtkostenController:index' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'App\\Controller\\FahrtkostenController:new' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'App\\Controller\\FahrtkostenController:show' => ['privates', '.service_locator.eHfDAxz', 'get_ServiceLocator_EHfDAxzService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.VWxzFOL', 'get_ServiceLocator_VWxzFOLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\FahrtkostenController::delete' => '?',
            'App\\Controller\\FahrtkostenController::edit' => '?',
            'App\\Controller\\FahrtkostenController::index' => '?',
            'App\\Controller\\FahrtkostenController::new' => '?',
            'App\\Controller\\FahrtkostenController::show' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\FahrtkostenController:delete' => '?',
            'App\\Controller\\FahrtkostenController:edit' => '?',
            'App\\Controller\\FahrtkostenController:index' => '?',
            'App\\Controller\\FahrtkostenController:new' => '?',
            'App\\Controller\\FahrtkostenController:show' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
