<?php

namespace ContainerBE0whLi;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFahrtkosten2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uSpJZaW.App\Entity\Fahrtkosten' shared service.
     *
     * @return \App\Entity\Fahrtkosten
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uSpJZaW": it references class "App\\Entity\\Fahrtkosten" but no such service exists.');
    }
}
