<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSY1Lafg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSY1Lafg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSY1Lafg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSY1Lafg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSY1Lafg\App_KernelDevDebugContainer([
    'container.build_hash' => 'SY1Lafg',
    'container.build_id' => 'eff76cbb',
    'container.build_time' => 1666008060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSY1Lafg');
